version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    